import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, "..");
const CONTENT_DIR = path.join(ROOT, "content");
const PAGES_DIR = path.join(CONTENT_DIR, "pages");
const OUT = path.join(ROOT, "src", "data", "content.json");
const ENV_OUT = path.join(ROOT, ".env.production.local");
const CNAME_OUT = path.join(ROOT, "public", "CNAME");

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

function loadPages() {
  const pages = {};
  if (!fs.existsSync(PAGES_DIR)) return pages;

  for (const file of fs.readdirSync(PAGES_DIR)) {
    if (!file.endsWith(".json")) continue;
    const name = path.basename(file, ".json");
    pages[name] = readJson(path.join(PAGES_DIR, file));
  }

  return pages;
}

function main() {
  const site = readJson(path.join(CONTENT_DIR, "site.json"));
  const pages = loadPages();

  const content = {
    ...site,
    pages,
    generatedAt: new Date().toISOString(),
  };

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, JSON.stringify(content, null, 2));

  const basePath =
    process.env.NEXT_PUBLIC_BASE_PATH !== undefined
      ? process.env.NEXT_PUBLIC_BASE_PATH
      : (site.basePath ?? "");
  fs.writeFileSync(
    ENV_OUT,
    `# Generated by scripts/build-content.mjs — do not edit\nNEXT_PUBLIC_BASE_PATH=${basePath}\n`
  );

  if (site.customDomain?.trim()) {
    fs.writeFileSync(CNAME_OUT, `${site.customDomain.trim()}\n`);
    console.log(`Custom domain: ${site.customDomain.trim()}`);
  } else if (fs.existsSync(CNAME_OUT)) {
    fs.unlinkSync(CNAME_OUT);
  }

  console.log(`Content built: ${Object.keys(pages).length} pages, basePath="${basePath}"`);
}

main();
