import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { loadPageContent, readJsonLenient } from "./lib/parse-content.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, "..");
const CONTENT_DIR = path.join(ROOT, "content");
const PAGES_DIR = path.join(CONTENT_DIR, "pages");
const OUT = path.join(ROOT, "src", "data", "content.json");
const ENV_OUT = path.join(ROOT, ".env.production.local");
const CNAME_OUT = path.join(ROOT, "public", "CNAME");

function loadPages() {
  const pages = {};
  if (!fs.existsSync(PAGES_DIR)) return pages;

  const pageNames = new Set();

  for (const file of fs.readdirSync(PAGES_DIR)) {
    if (file.endsWith(".txt")) {
      pageNames.add(file.slice(0, -4));
    } else if (file.endsWith(".meta.json")) {
      pageNames.add(file.slice(0, -".meta.json".length));
    } else if (file.endsWith(".json")) {
      pageNames.add(file.slice(0, -5));
    }
  }

  for (const name of [...pageNames].sort()) {
    pages[name] = loadPageContent(name, PAGES_DIR);
  }

  return pages;
}

function main() {
  const site = readJsonLenient(path.join(CONTENT_DIR, "site.json"));
  const pages = loadPages();

  const content = {
    ...site,
    pages,
    generatedAt: new Date().toISOString(),
  };

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, JSON.stringify(content, null, 2));

  const basePath =
    process.env.NEXT_PUBLIC_BASE_PATH !== undefined
      ? process.env.NEXT_PUBLIC_BASE_PATH
      : (site.basePath ?? "");
  fs.writeFileSync(
    ENV_OUT,
    `# Generated by scripts/build-content.mjs — do not edit\nNEXT_PUBLIC_BASE_PATH=${basePath}\n`
  );

  if (site.customDomain?.trim()) {
    fs.writeFileSync(CNAME_OUT, `${site.customDomain.trim()}\n`);
    console.log(`Custom domain: ${site.customDomain.trim()}`);
  } else if (fs.existsSync(CNAME_OUT)) {
    fs.unlinkSync(CNAME_OUT);
  }

  console.log(`Content built: ${Object.keys(pages).length} pages, basePath="${basePath}"`);
}

main();
